name: Deploy en EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar a EC2 y actualizar código del tema Kadence
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html/wp-content/themes/kadence
            git pull origin main
            sudo systemctl restart apache2 || sudo systemctl restart nginx

